version: '3.3'
services:
  api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9-slim
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8001:8000'
    restart: "no"
