version: '3.3'
services:
  api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9-slim
    logging:
      driver: json-file
    # command:
    #   - /start.sh
    #   - File=main.py  
    #   - if [ -f "$File" ]; then 
    #   - echo "$File exist"  
    #   - else  
    #   - echo "from fastapi import FastAPI" >> main.py
    #   - echo "app = FastAPI()" >> main.py
    #   - echo "@app.get("/")" >> main.py
    #   - echo "def hello_world():" >> main.py
    #   - echo "  return dict(message , 'OK')" >> main.py   
    #   - fi       
    #   - /start.sh
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8001:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - app:/app
    restart: 'no'
    networks:
      - webproxy
    deploy:
      replicas: 1
      labels:
        traefik.enable: 'true'
        traefik.docker.network: webproxy
        traefik.http.routers.spcn19fastapi02-http.entrypoints: http
        traefik.http.routers.spcn19fastapi02-http.rule: Host(`spcn19fastapi02.xops.ipv9.xyz`)
        traefik.http.services.spcn19fastapi02.loadbalancer.server.port: '8000'
        traefik.http.routers.spcn19fastapi02-http.middlewares: https-redirect
        traefik.http.routers.spcn19fastapi02-https.rule: Host(`spcn19fastapi02.xops.ipv9.xyz`)
        traefik.http.routers.spcn19fastapi02-https.entrypoints: https
        traefik.http.routers.spcn19fastapi02-https.tls: 'true'
      resources:
        reservations:
          cpus: '0.01'
          memory: '10m'
        limits:
          cpus: '0.4'
          memory: '50m'

networks:
  webproxy:
    external: true
volumes:
  app: