version: '3.3'
services:
  api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9-slim
    networks:
     - webproxy
    command:
     - /bin/bash
     - -c
     - |
       pip install fastapi uvicorn
       apt-get update
       apt-get install -y --no-install-recommends git
       apt-get install wget
       if [ -f "init" ]; then 
       echo ""
       else 
       rm main.py
       wget https://raw.githubusercontent.com/thanawat1303/swarm02/main/app/main.py
       touch init
       fi
       /start.sh
    environment:
     PORT: 8000
    logging:
      driver: json-file
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - app:/app
    restart: 'no'
    deploy:
      replicas: 1
      labels:
        - traefik.docker.network=webproxy
        - traefik.enable=true
        - traefik.constraint-label=webproxy
        - traefik.http.routers.spcn19fastapi-https.entrypoints=websecure
        - traefik.http.routers.spcn19fastapi-https.rule=Host("spcn19fastapi.xops.ipv9.xyz")
        - traefik.http.routers.spcn19fastapi-https.tls.certresolver=default
        - traefik.http.services.spcn19fastapi.loadbalancer.server.port=8000
        - traefik.http.routers.spcn19fastapi-https.tls=true
      resources:
        reservations:
          cpus: '0.1'
          memory: 10M
        limits:
          cpus: '0.4'
          memory: 250M
          
networks:
  webproxy:
    external: true
volumes:
  app:
    external: false